[package]
name = "bridge-relayer-v1"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.20", features = ["derive"] }
directories = "5.0.1"
futures = "0.3.31"
libp2p = { version = "0.54.1", features = ["dns", "ed25519", "gossipsub", "identify", "kad", "macros", "noise", "ping", "quic", "rendezvous", "tcp", "tokio", "websocket", "yamux"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sha3 = "0.10.8"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"

tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.14.0"
