services:
  bootstrap:
    image: bridge-validator-node:latest
    container_name: node_kdm_bootstrap
    ports:
      - "62649:62649/udp"
      - "62649:62649"
    networks:
      - bridge
    restart: unless-stopped

  client1:
    image: bridge-validator-node:latest
    container_name: node_kdm_client1
    ports:
      - "62650:62649/udp"
      - "62650:62649"
    networks:
      - bridge
  client2:
    image: bridge-validator-node:latest
    container_name: node_kdm_client2
    ports:
      - "62651:62649/udp"
      - "62651:62649"
    networks:
      - bridge

  client3:
    image: bridge-validator-node:latest
    container_name: node_kdm_client3
    ports:
      - "62652:62649/udp"
      - "62652:62649"
    networks:
      - bridge

  client4:
    image: bridge-validator-node:latest
    container_name: node_kdm_client4
    ports:
      - "62653:62649/udp"
      - "62653:62649"
    networks:
      - bridge

  client5:
    image: bridge-validator-node:latest
    container_name: node_kdm_client5
    ports:
      - "62654:62649/udp"
      - "62654:62649"
    networks:
      - bridge

networks:
  bridge:
  external:
    name: bridge

# Clean up
# docker system prune -f

# Construire l'image une seule fois
# docker build -t bridge-validator-node:latest .

# Démarrer les containers
# docker compose -f DockerCompose.yml up

# Ou en mode détaché
# docker compose -f DockerCompose.yml up -d

# ----------------------------------------------
# Build images without cache
# --------------------------------
# docker compose -f DockerCompose.yml build --no-cache

# Start containers
# ---------------------
# docker compose -f DockerCompose.yml up

# Start un seul conteneur
# ------------------------
# docker compose -f DockerCompose.yml up node_kdm_bootstrap

# Stop all containers
# ----------------------
# docker compose -f DockerCompose.yml down

# Stop all containers
# --------------------
# docker compose -f DockerCompose.yml stop node_kdm_client1

# Start a single container without rebuilding
# ------------------------
# docker compose -f DockerCompose.yml up --no-build node_kdm_bootstrap

# Execute the container in the background
# -------------------------------------
# docker compose -f DockerCompose.yml up -d node_kdm_bootstrap

# Connect to the container
# -------------------------
# docker exec --privileged -ti node_kdm_bootstrap /bin/bash