networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  bootstrap:
    image: libp2p-node:latest
    container_name: node_kdm_bootstrap
    ports:
      - "62649:62649/udp"
      - "62649:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.2
    restart: unless-stopped

  client1:
    image: libp2p-node:latest
    container_name: node_kdm_client1
    ports:
      - "62650:62649/udp"
      - "62650:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.3

  client2:
    image: libp2p-node:latest
    container_name: node_kdm_client2
    ports:
      - "62651:62649/udp"
      - "62651:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.4

  client3:
    image: libp2p-node:latest
    container_name: node_kdm_client3
    ports:
      - "62652:62649/udp"
      - "62652:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.5

  client4:
    image: libp2p-node:latest
    container_name: node_kdm_client4
    ports:
      - "62653:62649/udp"
      - "62653:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.6

  client5:
    image: libp2p-node:latest
    container_name: node_kdm_client5
    ports:
      - "62654:62649/udp"
      - "62654:62649"
    networks:
      bridge:
        ipv4_address: 172.21.0.7



# Clean up
# docker system prune -f

# Build image
# docker build -t libp2p-node:latest .

# Start containers
# docker compose -f DockerCompose.yml up


# peer ids
# --------
# bootstrap : 12D3KooWNHVedKDEa4ChsF4zvDJQE1ps1NJjhBsJictKMwzx6vya
# client1   : 12D3KooWRLMk7uaVWi7RsPPLvck89Rvcvk5g2kehoHNcyzkozJ1a
# client2   : 12D3KooWMfyCBFciZzncYS2fHdiqNJ6Ba1Lv6VYq7iAPfVKPJt32
# client3   : 12D3KooWSoor5UdaxVannUD2ga6A25TPaK2PnEWhpkCJPk783oxC
# client4   : 12D3KooWCUAiQHaLZYDXRkHacM1mEVtRCCvbQZJ6978KyyCUjrvD
# client5   : 12D3KooWPzeFxGTuvufCntVGbzAUof4uyQ4SpsTovZmDsK9ecrXb

# bootstrap
# docker exec -it node_kdm_bootstrap /bin/bash

# Validator
# docker exec -it node_kdm_client1 /bin/bash

# ----------------------------------------------
# Build images without cache
# --------------------------------
# docker compose -f DockerCompose.yml build --no-cache

# Start containers
# ---------------------
# docker compose -f DockerCompose.yml up

# Start only a specific container
# ------------------------
# docker compose -f DockerCompose.yml up node_kdm_bootstrap

# Stop all containers
# ----------------------
# docker compose -f DockerCompose.yml down

# Stop all containers
# --------------------
# docker compose -f DockerCompose.yml stop node_kdm_client1

# Start a single container without rebuilding
# ------------------------
# docker compose -f DockerCompose.yml up --no-build node_kdm_bootstrap

# Execute the container in the background
# -------------------------------------
# docker compose -f DockerCompose.yml up -d node_kdm_bootstrap

# Connect to the container
# -------------------------
# docker exec --privileged -ti node_kdm_bootstrap /bin/bash