services:
  bootstrap:
    image: bridge-validator-node:latest
    container_name: node_kdm_bootstrap
    ports:
      - "62649:62649/udp"
      - "62649:62649"
    networks:
      - bridge
    restart: unless-stopped

  client1:
    image: bridge-validator-node:latest
    container_name: node_kdm_client1
    ports:
      - "62650:62649/udp"
      - "62650:62649"
    networks:
      - bridge
  client2:
    image: bridge-validator-node:latest
    container_name: node_kdm_client2
    ports:
      - "62651:62649/udp"
      - "62651:62649"
    networks:
      - bridge

  client3:
    image: bridge-validator-node:latest
    container_name: node_kdm_client3
    ports:
      - "62652:62649/udp"
      - "62652:62649"
    networks:
      - bridge

  client4:
    image: bridge-validator-node:latest
    container_name: node_kdm_client4
    ports:
      - "62653:62649/udp"
      - "62653:62649"
    networks:
      - bridge

  client5:
    image: bridge-validator-node:latest
    container_name: node_kdm_client5
    ports:
      - "62654:62649/udp"
      - "62654:62649"
    networks:
      - bridge

networks:
  bridge:
  external:
    name: bridge

# Clean up
# docker system prune -f

# Construire l'image une seule fois
# docker build -t bridge-validator-node:latest .

# Démarrer les containers
# docker compose -f DockerCompose.yml up


# peer ids
# --------
# bootstrap : 12D3KooWNHVedKDEa4ChsF4zvDJQE1ps1NJjhBsJictKMwzx6vya
# client1   : 12D3KooWRLMk7uaVWi7RsPPLvck89Rvcvk5g2kehoHNcyzkozJ1a
# client2   : 12D3KooWMfyCBFciZzncYS2fHdiqNJ6Ba1Lv6VYq7iAPfVKPJt32
# client3   : 12D3KooWSoor5UdaxVannUD2ga6A25TPaK2PnEWhpkCJPk783oxC
# client4   : 12D3KooWCUAiQHaLZYDXRkHacM1mEVtRCCvbQZJ6978KyyCUjrvD
# client5   : 12D3KooWPzeFxGTuvufCntVGbzAUof4uyQ4SpsTovZmDsK9ecrXb

# bootstrap
# exec --privileged -ti node_kdm_bootstrap /bin/bash
# ./target/release/validator_node --new-peer-id --seed-phrase bootstrap
# 12D3KooWNHVedKDEa4ChsF4zvDJQE1ps1NJjhBsJictKMwzx6vya
# ./target/release/validator_node --node-kad --bootstrap --authorized-peer-id 1
#
# node regular sans message
# # docker exec --privileged -ti node_kdm_client1 /bin/bash
# ./target/release/validator_node --new-peer-id --seed-phrase client1
# 12D3KooWRLMk7uaVWi7RsPPLvck89Rvcvk5g2kehoHNcyzkozJ1a
# ./target/release/validator_node ./target/release/validator_node --node-kad --bootstrap-peer-id 12D3KooWNHVedKDEa4ChsF4zvDJQE1ps1NJjhBsJictKMwzx6vya --bootstrap-address <172.19.0.3> --authorized-peer-id 1
#
# node regular avec message
# # docker exec --privileged -ti node_kdm_client2 /bin/bash
# ./target/release/validator_node --new-peer-id
# ./target/release/validator_node ./target/release/validator_node --node-kad --bootstrap-peer-id 12D3KooWNHVedKDEa4ChsF4zvDJQE1ps1NJjhBsJictKMwzx6vya --bootstrap-address <172.19.0.3> --authorized-peer-id <peer-id>


# Ou en mode détaché
# docker compose -f DockerCompose.yml up -d

# ----------------------------------------------
# Build images without cache
# --------------------------------
# docker compose -f DockerCompose.yml build --no-cache

# Start containers
# ---------------------
# docker compose -f DockerCompose.yml up

# Start un seul conteneur
# ------------------------
# docker compose -f DockerCompose.yml up node_kdm_bootstrap

# Stop all containers
# ----------------------
# docker compose -f DockerCompose.yml down

# Stop all containers
# --------------------
# docker compose -f DockerCompose.yml stop node_kdm_client1

# Start a single container without rebuilding
# ------------------------
# docker compose -f DockerCompose.yml up --no-build node_kdm_bootstrap

# Execute the container in the background
# -------------------------------------
# docker compose -f DockerCompose.yml up -d node_kdm_bootstrap

# Connect to the container
# -------------------------
# docker exec --privileged -ti node_kdm_bootstrap /bin/bash